export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER_POSTS = "GET_CURRENT_USER_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
